//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INewGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        public int CommentID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblNew tblNew { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
