//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INewGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDailyDay
    {
        public int DailyDaysID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> TimeID { get; set; }
        public Nullable<int> AdsShedualsID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblAdsSchedule tblAdsSchedule { get; set; }
        public virtual tblDay tblDay { get; set; }
        public virtual tblTime tblTime { get; set; }
    }
}
