//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INewGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFavoritePageNew
    {
        public int FavoritesCategoryNewsID { get; set; }
        public Nullable<int> UserWallPageID { get; set; }
        public Nullable<int> CategoryIDNews { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblUserWallPage tblUserWallPage { get; set; }
    }
}
