//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INewGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHashtagNew
    {
        public int HashTagNewsID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public Nullable<int> HashtagID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LanguageID { get; set; }
    
        public virtual tblHashTag tblHashTag { get; set; }
        public virtual tblLanguage tblLanguage { get; set; }
        public virtual tblNew tblNew { get; set; }
    }
}
