//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INewGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLinkestan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLinkestan()
        {
            this.tblHashtagLinkestans = new HashSet<tblHashtagLinkestan>();
        }
    
        public int LikestanID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string LinkName { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHashtagLinkestan> tblHashtagLinkestans { get; set; }
        public virtual tblLanguage tblLanguage { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
