//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INewGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNew()
        {
            this.tblComments = new HashSet<tblComment>();
            this.tblHashtagNews = new HashSet<tblHashtagNew>();
            this.tblNewsLocations = new HashSet<tblNewsLocation>();
        }
    
        public int NewsID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<long> ViewNumber { get; set; }
        public string Link { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> RssID { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> Unlike { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComment> tblComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHashtagNew> tblHashtagNews { get; set; }
        public virtual tblRss tblRss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNewsLocation> tblNewsLocations { get; set; }
    }
}
