//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INewGN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPagePost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPagePost()
        {
            this.tblHashtagPagePosts = new HashSet<tblHashtagPagePost>();
            this.tblPagePostLocations = new HashSet<tblPagePostLocation>();
        }
    
        public int PagePostId { get; set; }
        public Nullable<int> UserWallPageID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> UnLike { get; set; }
        public Nullable<int> Visit { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHashtagPagePost> tblHashtagPagePosts { get; set; }
        public virtual tblUserWallPage tblUserWallPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPagePostLocation> tblPagePostLocations { get; set; }
    }
}
